# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:36:33+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, APIKeyQuery, BaseSecurity

from models import (
    FieldFormatDfsSlatesByDateDateGetResponse,
    FieldFormatPlayerGameProjectionStatsByDateDateGetResponse,
    FieldFormatPlayerGameProjectionStatsByPlayerDatePlayeridGetResponse,
    Format,
    Format1,
)

app = MCPProxy(
    contact={'x-twitter': 'nfldata'},
    description='LoL v3 Projections',
    title='LoL v3 Projections',
    version='1.0',
    servers=[
        {'url': 'http://azure-api.sportsdata.io/v3/lol/projections'},
        {'url': 'https://azure-api.sportsdata.io/v3/lol/projections'},
    ],
)


@app.get(
    '/{format}/DfsSlatesByDate/{date}',
    tags=['game_data_retrieval'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def dfs_slates_by_date(format: Format, date: str = ...):
    """
    Dfs Slates By Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByDate/{date}',
    description=""" Projected Player Game Stats by Date """,
    tags=['game_data_retrieval'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_game_stats_by_date(format: Format1 = 'xml', date: str = ...):
    """
    Projected Player Game Stats by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameProjectionStatsByPlayer/{date}/{playerid}',
    description=""" Projected Player Game Stats by Date """,
    tags=['game_data_retrieval'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def projected_player_game_stats_by_player(
    format: Format1 = 'xml', date: str = ..., playerid: str = ...
):
    """
    Projected Player Game Stats by Player
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
