# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:36:33+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class Game(BaseModel):
    BestOf: Optional[str] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DrawMoneyLine: Optional[int] = None
    GameId: Optional[int] = None
    Group: Optional[str] = None
    IsClosed: Optional[bool] = None
    PointSpread: Optional[float] = None
    RoundId: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Status: Optional[str] = None
    TeamAId: Optional[int] = None
    TeamAKey: Optional[str] = None
    TeamAMoneyLine: Optional[int] = None
    TeamAName: Optional[str] = None
    TeamAPointSpreadPayout: Optional[int] = None
    TeamAScore: Optional[int] = None
    TeamBId: Optional[int] = None
    TeamBKey: Optional[str] = None
    TeamBMoneyLine: Optional[int] = None
    TeamBName: Optional[str] = None
    TeamBPointSpreadPayout: Optional[int] = None
    TeamBScore: Optional[int] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    VenueId: Optional[int] = None
    VenueType: Optional[str] = None
    Week: Optional[int] = None
    Winner: Optional[str] = None


class PlayerGameProjection(BaseModel):
    Assists: Optional[float] = None
    CombatPlayerScore: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    Deaths: Optional[float] = None
    DoubleKills: Optional[float] = None
    FantasyPoints: Optional[float] = None
    GameId: Optional[int] = None
    Games: Optional[int] = None
    GoldEarned: Optional[float] = None
    GoldSpent: Optional[float] = None
    InhibitorKills: Optional[float] = None
    IsClosed: Optional[bool] = None
    KillingSpree: Optional[float] = None
    Kills: Optional[float] = None
    LargestCriticalStrike: Optional[float] = None
    LargestKillingSpree: Optional[float] = None
    LargestMultiKill: Optional[float] = None
    LongestTimeSpentLiving: Optional[float] = None
    MagicDamageDealt: Optional[float] = None
    MagicDamageDealtToChampions: Optional[float] = None
    MagicDamageTaken: Optional[float] = None
    MatchName: Optional[str] = None
    Matches: Optional[int] = None
    Name: Optional[str] = None
    NeutralMinionsKIlled: Optional[float] = None
    NeutralMinionsKIlledTeamJungle: Optional[float] = None
    NeutralMinionsKilledEnemyJungle: Optional[float] = None
    ObjectivePlayerScore: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentId: Optional[int] = None
    PentaKills: Optional[float] = None
    PhysicalDamageDealt: Optional[float] = None
    PhysicalDamageDealtToChampions: Optional[float] = None
    PhysicalDamageTaken: Optional[float] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    QuadraKills: Optional[float] = None
    SightWardsBoughtInGame: Optional[float] = None
    Team: Optional[str] = None
    TeamId: Optional[int] = None
    TenKillsOrAssists: Optional[float] = None
    TotalDamageDealt: Optional[float] = None
    TotalDamageDealtToChampions: Optional[float] = None
    TotalDamageTaken: Optional[float] = None
    TotalHeal: Optional[float] = None
    TotalMinionsKilled: Optional[float] = None
    TotalPlayerScore: Optional[float] = None
    TotalTimeCrowdControlDealt: Optional[float] = None
    TotalUnitsHealed: Optional[float] = None
    TripleKills: Optional[float] = None
    TrueDamageDealt: Optional[float] = None
    TrueDamageDealtToChampions: Optional[float] = None
    TrueDamageTaken: Optional[float] = None
    TurretKills: Optional[float] = None
    UnrealKills: Optional[float] = None
    Updated: Optional[str] = None
    VisionWardsBoughtInGame: Optional[float] = None
    WardsKilled: Optional[float] = None
    WardsPlaced: Optional[float] = None


class Format(Enum):
    json = 'json'
    xml = 'xml'


class FieldFormatPlayerGameProjectionStatsByDateDateGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class Format1(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatPlayerGameProjectionStatsByPlayerDatePlayeridGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class DfsSlate(BaseModel):
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None
    VideoGameId: Optional[int] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]
